name: devlab_fastapi-news_kafka

secrets:
  kafka_password:
    environment: ${KAFKA_PASSWORD}
    external: true
  app_secret:
    environment: ${APP_SECRET}
    external: true
  app_telegram_bot_token:
    environment: ${TELEGRAM_BOT_TOKEN}
    external: true
  app_telegram_bot_chat:
    environment: ${TELEGRAM_BOT_CHAT}
    external: true

networks:
  devlab_kafka:
    external: true

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    restart: unless-stopped
    networks:
      - devlab_kafka
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    # ports:
    #   - 22181:2181

  broker-1:
    image: confluentinc/cp-kafka:latest
    networks:
      - devlab_kafka
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-1:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: nc -z localhost 29092

  broker-2:
    image: confluentinc/cp-kafka:latest
    networks:
      - devlab_kafka
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker-2:29093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    healthcheck:
      test: nc -z localhost 29092

  # schema-registry:
  #   image: confluentinc/cp-schema-registry:latest
  #   restart: unless-stopped
  #   depends_on:
  #     - broker-1
  #   environment:
  #     SCHEMA_REGISTRY_HOST_NAME: schema-registry
  #     SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8085
  #     SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://broker-1:29092
  #     SCHEMA_REGISTRY_LOG4J_ROOT_LOGLEVEL: INFO

  akhq:
    image: tchiotludo/akhq
    restart: unless-stopped
    networks:
      - devlab_kafka
    environment:
      AKHQ_CONFIGURATION: |
        akhq:
          connections:
            docker-kafka-server:
              properties:
                bootstrap.servers: broker-1:29092
              schema-registry:
                url: http://schema-registry:8085
              connect:
                - name: "connect"
                  url: http://connect:8083
