from typing import Protocol, runtime_checkable

from app.lib import IAsyncContextManagerMixin


@runtime_checkable
class IEventBroker(Protocol, IAsyncContextManagerMixin):
    async def start(self): ...
    async def close(self): ...
    async def send(self, key: str, topic: str, msg: bytes): ...
    async def subscribe(self, topic: str): ...
    async def unsubscribe(self, topic: str): ...
